# Generated by Django 4.2.3 on 2023-10-27 18:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_id', models.CharField(max_length=200, unique=True)),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('expires_at', models.DateTimeField()),
                ('institution_id', models.CharField(max_length=200)),
                ('logo_url', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=200, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6)),
                ('value_date', models.DateTimeField()),
                ('description', models.CharField(max_length=500)),
                ('balance_after', models.DecimalField(decimal_places=2, max_digits=6)),
                ('debtor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('debtor_account', models.CharField(blank=True, max_length=200, null=True)),
                ('creditor_name', models.CharField(blank=True, max_length=200, null=True)),
                ('creditor_account', models.CharField(blank=True, max_length=200, null=True)),
                ('currency', models.CharField(max_length=50)),
                ('agreement', models.ManyToManyField(through='app.Account', to='app.agreements')),
            ],
        ),
        migrations.AddField(
            model_name='agreements',
            name='category',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.category'),
        ),
        migrations.AddField(
            model_name='account',
            name='agreements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.agreements'),
        ),
        migrations.AddField(
            model_name='account',
            name='transactions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.transactions'),
        ),
    ]
