# Generated by Django 4.2.3 on 2023-12-05 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='type',
            name='icon_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
