# Generated by Django 4.2.3 on 2023-10-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_account_agreements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='Working')),
                ('date_done', models.DateField()),
                ('affected_account', models.ManyToManyField(to='app.agreements')),
            ],
        ),
    ]
