# Generated by Django 4.2.3 on 2023-12-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_type_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='note',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
