# Generated by Django 4.2.3 on 2023-11-05 00:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_task_date_done_alter_transactions_value_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_done',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
