# Generated by Django 4.2.3 on 2023-11-05 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_transactions_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='balance_after',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
