# Generated by Django 4.2.3 on 2023-11-05 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_transactions_balance_after'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ('value_date',)},
        ),
    ]
