# Generated by Django 4.2.3 on 2023-11-05 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_transactions_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transactions',
            options={'ordering': ('-value_date',)},
        ),
    ]
