# Generated by Django 4.2.3 on 2023-11-07 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_transactions_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agreements',
            name='account',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.account'),
        ),
    ]
