# Generated by Django 4.2.3 on 2023-11-22 16:18

from django.db import migrations, models
import django.db.models.deletion
import django_regex.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_agreements_account'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TypeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule', django_regex.fields.RegexField()),
                ('type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.type')),
            ],
        ),
        migrations.AddField(
            model_name='transactions',
            name='type',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.type'),
        ),
    ]
