# Generated by Django 4.2.3 on 2023-11-22 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_type_typerule_transactions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='typerule',
            name='importance',
            field=models.IntegerField(default=0),
        ),
    ]
