# Generated by Django 4.2.3 on 2023-11-22 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_typerule_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='typerule',
            name='new_flag',
            field=models.BooleanField(default=True),
        ),
    ]
